spring:
    application:
        name:
            sb3t0
    datasource:
        url: jdbc:mysql://localhost:3306/sb3t0?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        username: sb3t0
        password: sb3t0
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            minimum-idle: 5
            maximum-pool-size: 10
            idle-timeout: 30000
            max-lifetime: 60000
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
    logging:
        level:
            com.zaxxer.hikari: DEBUG
            org.springframework.jdbc.datasource: DEBUG